set mypath=%~dp0

cd %mypath%

f:

cd "Application\KeyWordDriven\bin"

"C:\Program Files\Java\jdk1.8.0_101\bin\java" -cp %mypath%\Application\lib\cglib-nodep-3.2.4.jar;%mypath%\Application\lib\client-combined-3.0.1-nodeps.jar;%mypath%\Application\lib\commons-codec-1.10.jar;%mypath%\Application\lib\commons-exec-1.3.jar;%mypath%\Application\lib\commons-io-2.5.jar;%mypath%\Application\lib\commons-lang3-3.4.jar;%mypath%\Application\lib\commons-logging-1.2.jar;%mypath%\Application\lib\cssparser-0.9.20.jar;%mypath%\Application\lib\dom4j-1.6.jar;%mypath%\Application\lib\gson-2.3.1.jar;%mypath%\Application\lib\guava-19.0.jar;%mypath%\Application\lib\guava-23.0.jar;%mypath%\Application\lib\hamcrest-core-1.3.jar;%mypath%\Application\lib\hamcrest-library-1.3.jar;%mypath%\Application\lib\htmlunit-2.23.jar;%mypath%\Application\lib\htmlunit-core-js-2.23.jar;%mypath%\Application\lib\httpclient-4.5.2.jar;%mypath%\Application\lib\httpcore-4.4.4.jar;%mypath%\Application\lib\httpmime-4.5.2.jar;%mypath%\Application\lib\javax.servlet-api-3.1.0.jar;%mypath%\Application\lib\jcommander-1.29.jar;%mypath%\Application\lib\jetty-io-9.2.13.v20150730.jar;%mypath%\Application\lib\jetty-util-9.2.13.v20150730.jar;%mypath%\Application\lib\jna-4.1.0.jar;%mypath%\Application\lib\jna-platform-4.1.0.jar;%mypath%\Application\lib\junit-3.8.1.jar;%mypath%\Application\lib\junit-4.12.jar;%mypath%\Application\lib\junit-dep-4.10.jar;%mypath%\Application\lib\junit-dep-4.11.jar;%mypath%\Application\lib\log4j-1.2.17.jar;%mypath%\Application\lib\neko-htmlunit-2.23.jar;%mypath%\Application\lib\netty-3.5.7.Final.jar;%mypath%\Application\lib\phantomjsdriver-1.3.0.jar;%mypath%\Application\lib\poi-3.11-20141221.jar;%mypath%\Application\lib\poi-contrib-3.6-20091214.jar;%mypath%\Application\lib\poi-examples-3.11-20141221.jar;%mypath%\Application\lib\poi-ooxml-3.11-20141221.jar;%mypath%\Application\lib\poi-ooxml-schemas-3.11-20141221.jar;%mypath%\Application\lib\poi-scratchpad-3.11-20141221.jar;%mypath%\Application\lib\sac-1.3.jar;%mypath%\Application\lib\serializer-2.7.2.jar;%mypath%\Application\lib\testng-6.8.5.jar;%mypath%\Application\lib\websocket-api-9.2.15.v20160210.jar;%mypath%\Application\lib\websocket-client-9.2.15.v20160210.jar;%mypath%\Application\lib\websocket-common-9.2.15.v20160210.jar;%mypath%\Application\lib\xalan-2.7.2.jar;%mypath%\Application\lib\xercesImpl-2.11.0.jar;%mypath%\Application\lib\xml-apis-1.4.01.jar;%mypath%\Application\lib\xmlbeans-2.3.0.jar; driverScript.ExecuteTest


